\ ASCII BIG PATTERN TABLE ( 32 * 256 = 8192 (0X2000) )
2000 CONSTANT BIG_PATTERN_SIZE
CREATE BIG_PATTERN_TABLE  BIG_PATTERN_SIZE ALLOT 
BIG_PATTERN_TABLE BIG_PATTERN_SIZE ERASE

CREATE PATTERN_BUFFER 4 ALLOT
CREATE BIG_PATTERN
88 C, 78 C, 87 C, 77 C,  
  
: CREATE_BYTE ( byte -- )
  4 0 DO
    4 /MOD SWAP BIG_PATTERN + C@
    PATTERN_BUFFER 3 I - + C!
  LOOP DROP ;

: CREATE_PATTERN ( -- )
  100 0 DO
    8 0 DO
      ASCII_PATTERN_TABLE J 8 * + I + C@
      CREATE_BYTE
      PATTERN_BUFFER
      BIG_PATTERN_TABLE J 20 * + I 4 * + 
      4 CMOVE
    LOOP
  LOOP ;        
  
