\ Initialize.f

EMPTY
HEX
SYS-WARNING-OFF
WARNING OFF
' NOOP IS STACK-CHECK

\ Define words in FORTH for vocanulary operations 
VOCABULARY META
VOCABULARY TARGET
VOCABULARY FORWARD
VOCABULARY TRANSITION
VOCABULARY ASSEMBLER

' FORWARD VCFA>VOC CONSTANT FORWARD-WORDLIST
' TARGET  VCFA>VOC CONSTANT TARGET-WORDLIST

: IN-META ( -- ) ONLY FORTH ALSO META ALSO DEFINITIONS ;
: IN-TRANSITION ( -- ) ONLY FORWARD ALSO TARGET ALSO TRANSITION ;
: IN-ASSEMBLER ( -- ) ONLY FORTH ALSO ASSEMBLER DEFINITIONS ;