Fload USART_DeInit.f \ (USART_TypeDef* USARTx)
Fload USART_Init.f   \ (USART_TypeDef* USARTx, USART_InitTypeDef* USART_InitStruct)

\s
void USART_Init(USART_TypeDef* USARTx, USART_InitTypeDef* USART_InitStruct)
void USART_DeInit(USART_TypeDef* USARTx)
void USART_LINCmd(USART_TypeDef* USARTx, FunctionalState NewState)
void USART_SendBreak(USART_TypeDef* USARTx)
void USART_HalfDuplexCmd(USART_TypeDef* USARTx, FunctionalState NewState)
void USART_StructInit(USART_InitTypeDef* USART_InitStruct)
void USART_SetGuardTime(USART_TypeDef* USARTx, uint8_t USART_GuardTime)
void USART_ClockInit(USART_TypeDef* USARTx, USART_ClockInitTypeDef* USART_ClockInitStruct)
void USART_IrDAConfig(USART_TypeDef* USARTx, uint16_t USART_IrDAMode)
void USART_SmartCardNACKCmd(USART_TypeDef* USARTx, FunctionalState NewState)
void USART_SmartCardCmd(USART_TypeDef* USARTx, FunctionalState NewState)
void USART_SetPrescaler(USART_TypeDef* USARTx, uint8_t USART_Prescaler)
void USART_Cmd(USART_TypeDef* USARTx, FunctionalState NewState)
void USART_ClockStructInit(USART_ClockInitTypeDef* USART_ClockInitStruct)
void USART_ClearFlag(USART_TypeDef* USARTx, uint16_t USART_FLAG)
void USART_ClearITPendingBit(USART_TypeDef* USARTx, uint16_t USART_IT)
ITStatus USART_GetITStatus(USART_TypeDef* USARTx, uint16_t USART_IT)
FlagStatus USART_GetFlagStatus(USART_TypeDef* USARTx, uint16_t USART_FLAG)
void USART_ITConfig(USART_TypeDef* USARTx, uint16_t USART_IT, FunctionalState NewState)
void USART_DMACmd(USART_TypeDef* USARTx, uint16_t USART_DMAReq, FunctionalState NewState)
void USART_IrDACmd(USART_TypeDef* USARTx, FunctionalState NewState)
void USART_IrDAConfig(USART_TypeDef* USARTx, uint16_t USART_IrDAMode)
void USART_SmartCardNACKCmd(USART_TypeDef* USARTx, FunctionalState NewState)
void USART_SmartCardCmd(USART_TypeDef* USARTx, FunctionalState NewState)
void USART_SetGuardTime(USART_TypeDef* USARTx, uint8_t USART_GuardTime)
void USART_HalfDuplexCmd(USART_TypeDef* USARTx, FunctionalState NewState)
void USART_SendBreak(USART_TypeDef* USARTx)
void USART_LINCmd(USART_TypeDef* USARTx, FunctionalState NewState)
void USART_LINBreakDetectLengthConfig(USART_TypeDef* USARTx, uint16_t USART_LINBreakDetectLength)
void USART_WakeUpConfig(USART_TypeDef* USARTx, uint16_t USART_WakeUp)
void USART_ReceiverWakeUpCmd(USART_TypeDef* USARTx, FunctionalState NewState)
void USART_SetAddress(USART_TypeDef* USARTx, uint8_t USART_Address)
void USART_SendData(USART_TypeDef* USARTx, uint16_t Data)
void USART_OneBitMethodCmd(USART_TypeDef* USARTx, FunctionalState NewState)
void USART_OverSampling8Cmd(USART_TypeDef* USARTx, FunctionalState NewState)
void USART_SetPrescaler(USART_TypeDef* USARTx, uint8_t USART_Prescaler)
void USART_Cmd(USART_TypeDef* USARTx, FunctionalState NewState)
void USART_ClockStructInit(USART_ClockInitTypeDef* USART_ClockInitStruct)
void USART_ClockInit(USART_TypeDef* USARTx, USART_ClockInitTypeDef* USART_ClockInitStruct)
void USART_StructInit(USART_InitTypeDef* USART_InitStruct)
void USART_Init(USART_TypeDef* USARTx, USART_InitTypeDef* USART_InitStruct)
void USART_DeInit(USART_TypeDef* USARTx)
FlagStatus USART_GetFlagStatus(USART_TypeDef* USARTx, uint16_t USART_FLAG)
void USART_ITConfig(USART_TypeDef* USARTx, uint16_t USART_IT, FunctionalState NewState)
void USART_DMACmd(USART_TypeDef* USARTx, uint16_t USART_DMAReq, FunctionalState NewState)
void USART_IrDACmd(USART_TypeDef* USARTx, FunctionalState NewState)
void USART_SetAddress(USART_TypeDef* USARTx, uint8_t USART_Address)
void USART_SendData(USART_TypeDef* USARTx, uint16_t Data)
void USART_OneBitMethodCmd(USART_TypeDef* USARTx, FunctionalState NewState)
void USART_OverSampling8Cmd(USART_TypeDef* USARTx, FunctionalState NewState)
ITStatus USART_GetITStatus(USART_TypeDef* USARTx, uint16_t USART_IT)
void USART_ReceiverWakeUpCmd(USART_TypeDef* USARTx, FunctionalState NewState)
void USART_ClearFlag(USART_TypeDef* USARTx, uint16_t USART_FLAG)
void USART_ClearITPendingBit(USART_TypeDef* USARTx, uint16_t USART_IT)
void USART_LINBreakDetectLengthConfig(USART_TypeDef* USARTx, uint16_t USART_LINBreakDetectLength)
void USART_WakeUpConfig(USART_TypeDef* USARTx, uint16_t USART_WakeUp)