\ 0x4002 0000 - 0x4002 03FF

40020000 CONSTANT GPIO_A  
 0 4 * GPIO_A + CONSTANT GPIO_A->MODER   
 1 4 * GPIO_A + CONSTANT GPIO_A->OTYPER  
 2 4 * GPIO_A + CONSTANT GPIO_A->OSPEED  
 3 4 * GPIO_A + CONSTANT GPIO_A->PUPDR   
 4 4 * GPIO_A + CONSTANT GPIO_A->IDR     
 5 4 * GPIO_A + CONSTANT GPIO_A->ODR     
 6 4 * GPIO_A + CONSTANT GPIO_A->BSRR    
 7 4 * GPIO_A + CONSTANT GPIO_A->LCKR  
 8 4 * GPIO_A + CONSTANT GPIO_A->AFRL    
 9 4 * GPIO_A + CONSTANT GPIO_A->AFRH